#!/usr/bin/env python3
"""
Render client-specific MCP configs from the single source of truth in
mcp/servers.json.

Usage:
    python3 scripts/render-mcp-configs.py [--check]

Outputs go to mcp/rendered/. Rendered files contain placeholders for
secrets (e.g. ${N8N_MCP_AUTH_TOKEN}) — never real token values.

--check mode exits with code 1 if the rendered files on disk are out of
sync with what would be generated from the manifest. Useful for CI and
pre-commit hooks.

Dependencies: none (stdlib only). Works on any Python 3.x.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "mcp" / "servers.json"
RENDERED = ROOT / "mcp" / "rendered"


def load_manifest() -> dict[str, Any]:
    if not MANIFEST.exists():
        print(f"error: manifest not found at {MANIFEST}", file=sys.stderr)
        sys.exit(2)
    with MANIFEST.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, dict):
        print("error: manifest must be a JSON object at the top level", file=sys.stderr)
        sys.exit(2)
    return data


def servers_for_client(manifest: dict[str, Any], client_name: str) -> list[tuple[str, dict[str, Any]]]:
    out: list[tuple[str, dict[str, Any]]] = []
    for server_name, server in (manifest.get("servers") or {}).items():
        if client_name in (server.get("enabled_for") or []):
            out.append((server_name, server))
    out.sort(key=lambda pair: pair[0])  # stable order => deterministic diffs
    return out


def render_cowork(manifest: dict[str, Any], client_name: str, client: dict[str, Any]) -> str:
    servers = servers_for_client(manifest, client_name)
    lines: list[str] = [
        "# Claude Cowork — MCP connectors",
        "",
        "Generated by `scripts/render-mcp-configs.py` from `mcp/servers.json`.",
        "Do not edit this file manually — your changes will be overwritten.",
        "",
        f"Client: **{client_name}** — {client.get('description', '')}".rstrip(),
        "",
        "Cowork custom connectors are added through the UI",
        "(Settings → Custom MCP Connectors → Add). For each server below,",
        "create an entry with the listed URL and an `Authorization: Bearer …`",
        "header using the referenced secret.",
        "",
        "---",
        "",
    ]
    if not servers:
        lines.append("_No servers enabled for this client._")
        lines.append("")
        return "\n".join(lines)

    for name, server in servers:
        url = server["url"]
        auth = server.get("auth") or {}
        transport = server.get("transport", "http")
        description = (server.get("description") or "").strip()
        lines.append(f"## {name}")
        lines.append("")
        if description:
            lines.append(description)
            lines.append("")
        lines.append(f"- **URL**: `{url}`")
        lines.append(f"- **Transport**: `{transport}`")
        if auth.get("type") == "bearer":
            token_env = auth.get("token_env", "")
            lines.append(
                f"- **Header**: `Authorization: Bearer ${{{token_env}}}` "
                f"(value from `.env` variable `{token_env}` on the platform VM)"
            )
        else:
            lines.append(f"- **Auth**: `{auth or 'none'}`")
        notes = (server.get("notes") or "").strip()
        if notes:
            lines.append("")
            lines.append("**Notes:**")
            lines.append("")
            for note_line in notes.splitlines():
                lines.append(f"> {note_line}")
        lines.append("")
    return "\n".join(lines)


def render_codex(manifest: dict[str, Any], client_name: str, client: dict[str, Any]) -> str:
    servers = servers_for_client(manifest, client_name)
    config_path = client.get("config_path", "~/.codex/config.toml")
    lines: list[str] = [
        "# MCP server configuration for Codex CLI.",
        "#",
        "# Generated by scripts/render-mcp-configs.py from mcp/servers.json.",
        "# Do not edit this file manually — your changes will be overwritten.",
        "#",
        f"# Merge the blocks below into {config_path} (user-level) or into",
        "# a project-scoped .codex/config.toml (only inside a trusted project).",
        "#",
        "# Secrets are read from the environment via bearer_token_env_var, so",
        "# make sure the referenced variables are exported before launching Codex.",
        "",
    ]
    if not servers:
        lines.append("# No servers are enabled for this client.")
        lines.append("")
        return "\n".join(lines)

    for name, server in servers:
        transport = server.get("transport", "http")
        auth = server.get("auth") or {}
        description = (server.get("description") or "").strip()
        if description:
            lines.append(f"# {description}")
        lines.append(f"[mcp_servers.{name}]")
        if transport == "http":
            lines.append(f'url = "{server["url"]}"')
            if auth.get("type") == "bearer":
                lines.append(f'bearer_token_env_var = "{auth["token_env"]}"')
            else:
                lines.append(f"# WARNING: unsupported auth config: {auth}")
        else:
            lines.append(f"# WARNING: transport '{transport}' is not supported")
            lines.append("#   by the Codex renderer yet. Update render-mcp-configs.py")
            lines.append("#   when adding a new transport.")
        lines.append("")
    return "\n".join(lines)


RENDERERS = {
    "cowork-custom-connector": ("claude-cowork.md", render_cowork),
    "codex-cli": ("codex.toml", render_codex),
}


def generate(manifest: dict[str, Any]) -> dict[Path, str]:
    out: dict[Path, str] = {}
    for client_name, client in (manifest.get("clients") or {}).items():
        kind = client.get("kind")
        if kind not in RENDERERS:
            print(
                f"warning: client '{client_name}' has unknown kind '{kind}', skipping",
                file=sys.stderr,
            )
            continue
        filename, renderer = RENDERERS[kind]
        out[RENDERED / filename] = renderer(manifest, client_name, client)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if rendered files are out of sync with the manifest.",
    )
    args = parser.parse_args()

    manifest = load_manifest()
    generated = generate(manifest)

    if args.check:
        drift = False
        for path, content in generated.items():
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                print(f"out of sync: {path.relative_to(ROOT)}")
                drift = True
        if drift:
            print(
                "\nRun: python3 scripts/render-mcp-configs.py",
                file=sys.stderr,
            )
            return 1
        print("mcp/rendered/ matches mcp/servers.json")
        return 0

    RENDERED.mkdir(parents=True, exist_ok=True)
    for path, content in generated.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
